name: dns_toggle
description: DNS toggle with Quick Settings tile
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_vpn_service: ^1.1.0
  quick_settings: ^1.0.0+2
  flutter_local_notifications: ^17.2.3

flutter:
  uses-material-design: true
